# Generated by Django 3.2 on 2021-06-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha llenado')),
                ('hora_llenado', models.TimeField(verbose_name='Hora llenado')),
                ('placa', models.IntegerField(choices=[[0, 'C339BPH'], [1, 'C386BLD'], [2, 'C649BKM'], [3, 'C511BNL'], [4, 'C856BLY'], [5, 'C910BNX'], [6, 'C306BPR']], verbose_name='Placa')),
                ('piloto', models.IntegerField(choices=[[0, 'LESTER ZEPEDA'], [1, 'BYRON BLASS'], [2, 'ALLAN GOMEZ'], [3, 'EDUARDO BONILLA'], [4, 'DARWIN VARGAS'], [5, 'LUIS JIMENEZ'], [6, 'ABRAHAM MARTINEZ']], verbose_name='Piloto')),
                ('ruta', models.IntegerField(choices=[[0, 'BAR1'], [1, 'BAR2'], [2, 'JAL1'], [3, 'JAL2'], [4, 'JUT1'], [5, 'JUT2'], [6, 'JUT3']], verbose_name='Ruta')),
                ('serie', models.CharField(max_length=50, verbose_name='Serie Factura')),
                ('no_factura', models.IntegerField(verbose_name='Numero de Factura')),
                ('total', models.FloatField(verbose_name='Total Llenado')),
                ('galones', models.FloatField(verbose_name='Galones Llenados')),
                ('tipo_combustible', models.CharField(max_length=50, verbose_name='Tipo de Combustible')),
                ('bomnba', models.IntegerField(verbose_name='Bomba Lllenado')),
                ('precioxgalon', models.FloatField(verbose_name='Precio Por Galon')),
                ('kminicial', models.IntegerField(verbose_name='Kilometro Inicial')),
                ('kmfinal', models.IntegerField(verbose_name='Kilometro Final')),
                ('recorrido', models.IntegerField(verbose_name='Recorrido')),
                ('rendxgalon', models.FloatField(verbose_name='Rendimiento Por Galon')),
                ('manifiesto', models.IntegerField(verbose_name='Manifiesto')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
            ],
        ),
    ]
